version: '3.8'

services:
  airline-app:
    build: .
    container_name: airline-app
    depends_on:
      - airline-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://airline-db:5432/airline
      SPRING_DATASOURCE_USERNAME: myusername
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
      JWT_SECRET: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    ports:
      - "8000:8000"
    restart: unless-stopped

  airline-db:
    image: postgres:15
    container_name: airline-db
    environment:
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: airline
    ports:
      - "15432:5432"
    volumes:
      - airline-db-data:/var/lib/postgresql/data

volumes:
  airline-db-data:
    driver: local
